# Copyright (c) 2025 Environmental Systems Research Institute, Inc.
# SPDX-License-Identifier: Apache-2.0

name: Build and test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  #schedule:
  #  - cron: '42 1 * * *'
  #    timezone: "America/Los_Angeles"

jobs:
  build:
    #if: github.repository == 'esri/link-what-you-include'
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-24.04, windows-2025-vs2026, macos-26]

    steps:
      - name: Setup windows environment
        if: runner.os == 'Windows'
        uses: TheMrMilchmann/setup-msvc-dev@v4
        with:
          arch: x64

      - name: Setup linux environment
        if: runner.os == 'Linux'
        run: |
          sudo apt install clang-tidy-20
          echo "CXX=/usr/bin/g++-14" >> $GITHUB_ENV
          echo "CC=/usr/bin/gcc-14" >> $GITHUB_ENV

      - name: Setup macos environment
        if: runner.os == 'MacOS'
        run: |
          sudo xcode-select -switch /Library/Developer/CommandLineTools
          brew install llvm@21
          echo "SDKROOT=$(xcrun --show-sdk-path)" >> $GITHUB_ENV
          echo "CXX=$(brew --prefix llvm@21)/bin/clang++" >> $GITHUB_ENV
          echo "CC=$(brew --prefix llvm@21)/bin/clang" >> $GITHUB_ENV

      - name: Checkout
        uses: actions/checkout@v6

      - name: Cache 3rdparty
        id: cache-3rdparty
        uses: actions/cache@v5
        with:
          path: ./3rdparty
          key: ${{ runner.os }}-3rdparty-${{ hashFiles('tools/build_*.sh') }}

      - name: Build 3rdparty
        if: steps.cache-3rdparty.outputs.cache-hit != 'true'
        shell: bash
        run: |
          bash ./tools/build_catch2.sh
          bash ./tools/build_clangtooling.sh
          bash ./tools/build_simdjson.sh

      - name: Enable 3rdparty
        shell: bash
        run: |
          echo "CMAKE_PREFIX_PATH=$GITHUB_WORKSPACE/3rdparty" >> $GITHUB_ENV

      - name: Build and test
        shell: ctest -VV -S {0}
        run: |
          include($ENV{GITHUB_WORKSPACE}/.github/workflows/common_ctest.cmake)

          set(CTEST_CONFIGURATION_TYPE Release)
          set(CTEST_SOURCE_DIRECTORY $ENV{GITHUB_WORKSPACE})
          set(CTEST_BINARY_DIRECTORY $ENV{GITHUB_WORKSPACE}/build/release)
          set(CTEST_BUILD_NAME ${CMAKE_SYSTEM_NAME}.${CTEST_CONFIGURATION_TYPE})

          set(model Experimental)
          if($ENV{GITHUB_EVENT_NAME} STREQUAL schedule)
            set(model Nightly)
          endif()

          set(configure_opts
            -DCMAKE_INSTALL_PREFIX=$ENV{GITHUB_WORKSPACE}/install
            )

          ctest_start(${model})
          ctest_update()
          ctest_configure(OPTIONS "${configure_opts}")
          ctest_build()
          ctest_test()
          ctest_submit()

      - name: Install
        run: |
          cmake --install ./build/release

      - name: Upload Install
        uses: actions/upload-artifact@v4
        with:
          name: lwyi_${{ runner.os }}
          path: install
          retention-days: 5

      - name: Clang-tidy
        if: runner.os == 'Linux'
        shell: ctest -VV -S {0}
        run: |
          include($ENV{GITHUB_WORKSPACE}/.github/workflows/common_ctest.cmake)

          set(CTEST_CONFIGURATION_TYPE Release)
          set(CTEST_SOURCE_DIRECTORY $ENV{GITHUB_WORKSPACE})
          set(CTEST_BINARY_DIRECTORY $ENV{GITHUB_WORKSPACE}/build/tidy)
          set(CTEST_BUILD_NAME ${CMAKE_SYSTEM_NAME}.clang-tidy)

          set(model Experimental)
          if($ENV{GITHUB_EVENT_NAME} STREQUAL schedule)
            set(model Nightly)
          endif()

          set(configure_opts
            -DCMAKE_CXX_CLANG_TIDY=/usr/bin/clang-tidy-20
            )

          ctest_start(${model})
          ctest_update()
          ctest_configure(OPTIONS "${configure_opts}")
          ctest_build()
          ctest_submit()

      - name: Coverage
        if: github.event_name == 'schedule' && runner.os == 'Linux'
        shell: ctest -VV -S {0}
        run: |
          include($ENV{GITHUB_WORKSPACE}/.github/workflows/common_ctest.cmake)

          set(CTEST_CONFIGURATION_TYPE Debug)
          set(CTEST_SOURCE_DIRECTORY $ENV{GITHUB_WORKSPACE})
          set(CTEST_BINARY_DIRECTORY $ENV{GITHUB_WORKSPACE}/build/coverage)
          set(CTEST_BUILD_NAME ${CMAKE_SYSTEM_NAME}.coverage)

          find_program(CTEST_COVERAGE_COMMAND NAMES gcov)
          set(configure_opts
            -DCMAKE_CXX_FLAGS_INIT=--coverage
            )

          ctest_start(Nightly)
          ctest_update()
          ctest_configure(OPTIONS "${configure_opts}")
          ctest_build()
          ctest_test()
          ctest_coverage()
          ctest_submit()

      - name: ASan
        if: github.event_name == 'schedule' && runner.os == 'Linux'
        shell: ctest -VV -S {0}
        run: |
          include($ENV{GITHUB_WORKSPACE}/.github/workflows/common_ctest.cmake)

          set(CTEST_CONFIGURATION_TYPE Debug)
          set(CTEST_SOURCE_DIRECTORY $ENV{GITHUB_WORKSPACE})
          set(CTEST_BINARY_DIRECTORY $ENV{GITHUB_WORKSPACE}/build/asan)
          set(CTEST_BUILD_NAME ${CMAKE_SYSTEM_NAME}.asan)

          set(CTEST_MEMORYCHECK_TYPE AddressSanitizer)

          set(configure_opts
            -DCMAKE_CXX_FLAGS_INIT=-fsanitize=address
            -DCMAKE_EXE_LINKER_FLAGS_INIT=-fsanitize=address
            )

          ctest_start(Nightly)
          ctest_update()
          ctest_configure(OPTIONS "${configure_opts}")
          ctest_build()
          ctest_memcheck()
          ctest_submit()
