name: LWYI CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-24.04, windows-2025]
    defaults:
      run:
        shell: ${{ startsWith(matrix.os, 'windows') && 'cmd' || 'bash' }}  

    steps:
      - name: Setup Conan
        uses: conan-io/setup-conan@v1
        with:
          audit_token: ${{ secrets.CONAN_AUDIT_TOKEN }}

      - name: Checkout
        uses: actions/checkout@v4

      - name: Install libclang on ubuntu
        if: ${{ startsWith(matrix.os, 'ubuntu') }}  
        run: |
          sudo apt install -y libclang-18-dev
          echo "Clang_ROOT=/usr/lib/llvm-18" >> "$GITHUB_ENV"

      - name: Install libclang on windows
        if: ${{ startsWith(matrix.os, 'windows') }}  
        shell: cmake -P {0}
        run: |
          set(QT_MIRRORS
            download.qt.io
            mirrors.ocf.berkeley.edu/qt
            ftp.fau.de/qtproject
            mirrors.sau.edu.cn/qt
            )
          foreach(qt_mirror ${QT_MIRRORS})
            set(libclang_url https://${qt_mirror}/development_releases/prebuilt/libclang/libclang-release_18.1.7-based-windows-vs2019_64.7z)
            foreach(retry RANGE 10)
              file(DOWNLOAD ${libclang_url} ./libclang.7z)
              file(SIZE ./libclang.7z fileSize)
              if(fileSize GREATER 0)
                break()
              endif()
            endforeach()

            file(SIZE ./libclang.7z fileSize)
            if (fileSize GREATER 0)
              break()
            endif()
          endforeach()

          execute_process(COMMAND ${CMAKE_COMMAND} -E tar xvf ./libclang.7z)

          file(TO_CMAKE_PATH "$ENV{GITHUB_WORKSPACE}/libclang" libclang_dir)
          file(APPEND "$ENV{GITHUB_ENV}" "Clang_ROOT=${libclang_dir}\n")

      - name: Conan install
        shell: bash
        run: |
          conan install . -s compiler.cppstd=17 -s build_type=Release --build=missing -of build
          echo "CMAKE_TOOLCHAIN_FILE=$GITHUB_WORKSPACE/build/conan_build/generators/conan_toolchain.cmake" >> $GITHUB_ENV

      - name: Build on Linux
        if: ${{ startsWith(matrix.os, 'ubuntu') }}  
        run: |
          cmake -S. -Bbuild -GNinja -DCMAKE_BUILD_TYPE=Release
          cmake --build build

      - name: Build on Windows
        if: ${{ startsWith(matrix.os, 'windows') }}  
        run: |
          call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
          cmake -S. -Bbuild -GNinja -DCMAKE_BUILD_TYPE=Release
          cmake --build build

      - name: Run tests
        run: |
          cd build
          ctest --output-on-failure
