name: LWYI CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-24.04, windows-2025]
    defaults:
      run:
        shell: ${{ startsWith(matrix.os, 'windows') && 'cmd' || 'bash' }}  

    steps:
      - name: Setup Conan
        uses: conan-io/setup-conan@v1
        with:
          audit_token: ${{ secrets.CONAN_AUDIT_TOKEN }}

      - name: Checkout
        uses: actions/checkout@v4

      - name: Install libclang on ubuntu
        if: ${{ startsWith(matrix.os, 'ubuntu') }}  
        run: |
          sudo apt install -y libclang-18-dev
          echo "Clang_ROOT=/usr/lib/llvm-18" >> "$GITHUB_ENV"

      - name: Install libclang on windows
        if: ${{ startsWith(matrix.os, 'windows') }}  
        shell: bash
        run: |
          llvmArchive="clang+llvm-18.1.8-x86_64-pc-windows-msvc.tar.xz"
          llvmUrl="https://github.com/llvm/llvm-project/releases/download/llvmorg-18.1.8/$llvmArchive"
          installDir="llvm-18.1.8"
          mkdir $installDir
          echo "url: $llvmUrl"
          curl -L -o $llvmArchive $llvmUrl
          tar -xf $llvmArchive -C $installDir --strip-components=1
          echo "Clang_ROOT=$GITHUB_WORKSPACE/$installDir" >> $GITHUB_ENV

      - name: Conan install
        run: |
          conan install . -s compiler.cppstd=17 -s build_type=Release --build=missing -of build
          echo "CMAKE_TOOLCHAIN_FILE=$GITHUB_WORKSPACE/build/conan_build/generators/conan_toolchain.cmake" >> $GITHUB_ENV

      - name: MSVC environment
        if: ${{ startsWith(matrix.os, 'windows') }}  
        run: |
          call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvars64.bat"

      - name: Build
        run: |
          cmake -S. -Bbuild -GNinja -DCMAKE_BUILD_TYPE=Release
          cmake --build build

      - name: Run tests
        run: |
          cd build
          ctest --output-on-failure
