# Copyright (c) 2025 Environmental Systems Research Institute, Inc.
# SPDX-License-Identifier: Apache-2.0

name: Simple build and test

on:
  schedule:
    - cron: '42 2 * * *'
      timezone: "America/Los_Angeles"
  workflow_dispatch:

jobs:
  build:
    if: github.repository == 'esri/link-what-you-include' || github.event_name == 'workflow_dispatch'
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-26.04, macos-26]

    steps:
      - name: Setup linux environment
        if: runner.os == 'Linux'
        # update README.md if this is changed
        run: |
          sudo apt install clang-18 libclang-18-dev libsimdjson-dev catch2
          echo "Clang_ROOT=/usr/lib/llvm-18" >> $GITHUB_ENV
          echo "CMAKE_GENERATOR=Ninja" >> $GITHUB_ENV

      - name: Setup macos environment
        if: runner.os == 'MacOS'
        # update README.md if this is changed
        run: |
          sudo xcode-select -switch /Library/Developer/CommandLineTools
          brew install llvm@21 llvm@18 catch2 simdjson
          echo "SDKROOT=$(xcrun --show-sdk-path)" >> $GITHUB_ENV
          echo "CXX=$(brew --prefix llvm@21)/bin/clang++" >> $GITHUB_ENV
          echo "CC=$(brew --prefix llvm@21)/bin/clang" >> $GITHUB_ENV
          echo "Clang_ROOT=/opt/homebrew/opt/llvm@18" >> $GITHUB_ENV
          echo "Catch2_ROOT=/opt/homebrew/Cellar/catch2/3.15.1" >> $GITHUB_ENV
          echo "simdjson_ROOT=/opt/homebrew/Cellar/simdjson/4.6.4" >> $GITHUB_ENV
          echo "CMAKE_GENERATOR=Ninja" >> $GITHUB_ENV

      - name: Checkout
        uses: actions/checkout@v6

      - name: Build and test
        run: |
          cmake -S . -B build -DCMAKE_BUILD_TYPE=Debug
          cmake --build build 
          ctest --test-dir build 

